language: objective-c

branches:
  only:
  - master

before_install:
  - brew update

xcode_project: mongod-starter.xcodeproj
xcode_scheme: mongod-starter
osx_image: xcode8
xcode_sdk: macosx10.11

script:
  xcodebuild clean build test -project mongod-starter.xcodeproj -scheme mongod-starter

